> plot_3 <- subset(NEI_SCC, fips == "24510", c("Emissions", "Year","type"))
> plot_3 <- melt(plot_3, id=c("Year", "type"), measure.vars=c("Emissions"))
> plot_3 <- dcast(plot_3, Year + type ~ variable, sum)
> ggplot(data=plot_3, aes(x=Year, y=Emissions, group=type, color=type)) + geom_line() + geom_point( size=4, shape=21, fill="white") + xlab("Year") + ylab("Emissions (tons)") + ggtitle("Baltimore PM2.5 Emissions by Type and Year")
> ggsave(file="plot_3.png")